      SUBROUTINE MVKBRVEVAL( NDIM, MAXVLS, NF,
     &                       ABSEPS, RELEPS, ABSERR, FINEST,
     &                       INFORM, MINVLS )
      EXTERNAL MVKBRVINTEGRAND
      DOUBLE PRECISION ABSEPS, RELEPS, FINEST(*), ABSERR
      INTEGER NDIM, NF, MINVLS, MAXVLS, INFORM

      CALL MVKBRV( NDIM, MINVLS, MAXVLS, NF,
     &             MVKBRVINTEGRAND, ABSEPS, RELEPS,
     &             ABSERR, FINEST, INFORM )

      END
