# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_log_lm_terms_cpp <- function(lower, upper, code) {
    .Call(`_mdgc_get_log_lm_terms_cpp`, lower, upper, code)
}

eval_log_lm_terms <- function(ptr, indices, vcov, maxpts, abs_eps, rel_eps, n_threads, comp_derivs, minvls, do_reorder = TRUE, use_aprx = FALSE) {
    .Call(`_mdgc_eval_log_lm_terms`, ptr, indices, vcov, maxpts, abs_eps, rel_eps, n_threads, comp_derivs, minvls, do_reorder, use_aprx)
}

get_z_hat <- function(lower, upper, code, n_threads) {
    .Call(`_mdgc_get_z_hat`, lower, upper, code, n_threads)
}

pmvnorm <- function(lower, upper, mu, Sigma, maxvls, abs_eps, rel_eps, derivs, do_reorder = TRUE, use_aprx = FALSE) {
    .Call(`_mdgc_pmvnorm_to_R`, lower, upper, mu, Sigma, maxvls, abs_eps, rel_eps, derivs, do_reorder, use_aprx)
}

get_commutation <- function(n, m) {
    .Call(`_mdgc_get_commutation_to_R`, n, m)
}

get_commutation_vec <- function(n, m, transpose) {
    .Call(`_mdgc_get_commutation_vec`, n, m, transpose)
}

x_dot_X_kron_I <- function(x, X, l) {
    .Call(`_mdgc_x_dot_X_kron_I_wrap`, x, X, l)
}

impute <- function(lower, upper, code, Sigma, truth, margs, rel_eps, abs_eps, maxit, passed_names, outer_names, n_threads, do_reorder, minvls, use_aprx = FALSE) {
    .Call(`_mdgc_impute`, lower, upper, code, Sigma, truth, margs, rel_eps, abs_eps, maxit, passed_names, outer_names, n_threads, do_reorder, minvls, use_aprx)
}

