# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_log_lm_terms <- function(lower, upper, code) {
    .Call(`_mdgc_get_log_lm_terms`, lower, upper, code)
}

eval_log_lm_terms <- function(ptr, indices, vcov, maxpts, abseps, releps, n_threads, comp_derivs, do_reorder = TRUE) {
    .Call(`_mdgc_eval_log_lm_terms`, ptr, indices, vcov, maxpts, abseps, releps, n_threads, comp_derivs, do_reorder)
}

